#!/bin/bash
# ---------------------------------------------------------
# build.sh for forbidden_forest_1983_cosmi
# Auto-generated by d64toasm.sh from Forbidden_Forest_1983_Cosmi.d64
#
# Usage:
#   ./build.sh          Build only
#   ./build.sh run      Build and launch in VICE (x64sc)
#   ./build.sh debug    Build and launch with debug symbols
# ---------------------------------------------------------
set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
C64_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
KICKASS="$C64_ROOT/KickAssembler/KickAss.jar"
BUILD_DIR="$SCRIPT_DIR/build"

if [[ "$(uname -m)" == "arm64" ]]; then
    VICE_DIR="$C64_ROOT/vice-arm64-sdl2-3.10"
else
    VICE_DIR="$C64_ROOT/vice-x86-64-sdl2-3.10"
fi

GREEN='\033[0;32m'
RED='\033[0;31m'
CYAN='\033[0;36m'
NC='\033[0m'

VICE_CFG="$HOME/.config/vice/sdl-vicerc"
C1541="$VICE_DIR/bin/c1541"
ORIG_D64="$SCRIPT_DIR/Forbidden_Forest_1983_Cosmi.d64"
TEST_D64="$BUILD_DIR/test.d64"

_build_test_d64() {
    cp "$ORIG_D64" "$TEST_D64"
    "$C1541" -attach "$TEST_D64" -delete "forbidden loader" -write "$BUILD_DIR/forbidden_loader.prg" "forbidden loader" > /dev/null 2>&1
    "$C1541" -attach "$TEST_D64" -delete "forbidden game" -write "$BUILD_DIR/forbidden_game.prg" "forbidden game" > /dev/null 2>&1
    echo -e "${CYAN}  Injected built PRGs into test.d64${NC}"
}
mkdir -p "$BUILD_DIR"
echo -e "${CYAN}=== Building: forbidden_forest_1983_cosmi ===${NC}"
echo ""

    echo -e "${CYAN}  Assembling forbidden_loader.asm...${NC}"
    if ! java -jar "$KICKASS" "$SCRIPT_DIR/forbidden_loader.asm" -o "$BUILD_DIR/forbidden_loader.prg"; then
        echo -e "${RED}FAILED: forbidden_loader.asm${NC}"
        exit 1
    fi
    echo -e "${CYAN}  Assembling forbidden_game.asm...${NC}"
    if ! java -jar "$KICKASS" "$SCRIPT_DIR/forbidden_game.asm" -o "$BUILD_DIR/forbidden_game.prg"; then
        echo -e "${RED}FAILED: forbidden_game.asm${NC}"
        exit 1
    fi

echo ""
echo -e "${GREEN}Build successful!${NC} -> $BUILD_DIR/forbidden_loader.prg"

if [ "$1" = "run" ]; then
    echo ""
    echo -e "${CYAN}Launching in VICE (x64sc)...${NC}"
    _build_test_d64
    open -a "$VICE_DIR/VICE.app" --args --program x64sc -config "$VICE_CFG" -autostart "$TEST_D64"
fi

if [ "$1" = "debug" ]; then
    echo ""
    echo -e "${CYAN}Launching in VICE with debug symbols...${NC}"
    _build_test_d64
    SYM_FILE="$SCRIPT_DIR/forbidden_game.sym"
    open -a "$VICE_DIR/VICE.app" --args --program x64sc -config "$VICE_CFG" -moncommands "$SYM_FILE" -autostart "$TEST_D64"
    echo -e "${GREEN}VICE started with labels loaded.${NC}"
fi
