#!/bin/bash
# ---------------------------------------------------------
# build.sh for 1476_forbidden_forest
# Auto-generated by d64toasm.sh from 1476 FORBIDDEN FOREST.D64
#
# Usage:
#   ./build.sh          Build only
#   ./build.sh run      Build and launch in VICE (x64sc)
#   ./build.sh debug    Build and launch with debug symbols
# ---------------------------------------------------------
set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
C64_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
KICKASS="$C64_ROOT/KickAssembler/KickAss.jar"
BUILD_DIR="$C64_ROOT/build"

if [[ "$(uname -m)" == "arm64" ]]; then
    VICE_DIR="$C64_ROOT/vice-arm64-sdl2-3.10"
else
    VICE_DIR="$C64_ROOT/vice-x86-64-sdl2-3.10"
fi

GREEN='\033[0;32m'
RED='\033[0;31m'
CYAN='\033[0;36m'
NC='\033[0m'

VICE_CFG="$HOME/.config/vice/sdl-vicerc"

mkdir -p "$BUILD_DIR"
echo -e "${CYAN}=== Building: 1476_forbidden_forest ===${NC}"
echo ""

    echo -e "${CYAN}  Assembling forbidden_forest.asm...${NC}"
    if ! java -jar "$KICKASS" "$SCRIPT_DIR/forbidden_forest.asm" -debugdump -debug -symbolfile -o "$BUILD_DIR/main.prg"; then
        echo -e "${RED}FAILED: forbidden_forest.asm${NC}"
        exit 1
    fi

echo ""
echo -e "${GREEN}Build successful!${NC} -> $BUILD_DIR/main.prg"

if [ "$1" = "run" ]; then
    echo ""
    echo -e "${CYAN}Launching in VICE (x64sc)...${NC}"

    open -a "$VICE_DIR/VICE.app" --args --program x64sc -config "$VICE_CFG" -autostart "$BUILD_DIR/main.prg"
fi

if [ "$1" = "debug" ]; then
    echo ""
    echo -e "${CYAN}Launching in VICE with debug symbols...${NC}"

    SYM_FILE="$SCRIPT_DIR/forbidden_forest.sym"
    open -a "$VICE_DIR/VICE.app" --args --program x64sc -config "$VICE_CFG" -moncommands "$SYM_FILE" -autostart "$BUILD_DIR/main.prg"
    echo -e "${GREEN}VICE started with labels loaded.${NC}"
fi
